# Generated by Django 3.1.6 on 2021-02-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='company_email',
            new_name='email',
        ),
    ]
