# Generated by Django 3.1.6 on 2021-02-17 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='Annual Leave', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(default='Not Feeling Well', max_length=1200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employers')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Department_cmpid',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('request', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], default='reject', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department_cmpid')),
            ],
        ),
    ]
