# Generated by Django 3.1.6 on 2021-02-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], default='reject', max_length=10),
        ),
    ]
