# Generated by Django 3.1.6 on 2021-02-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='department',
        ),
    ]
