# Generated by Django 3.1.6 on 2021-02-17 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('employee', '0005_auto_20210217_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(auto_now_add=True)),
                ('to_date', models.DateField(auto_now_add=True)),
                ('salary', models.IntegerField(max_length=1000000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employers')),
            ],
        ),
    ]
